### ISSUE TITLE
support video capture rotation

### ISSUE THREAD

**Issue by aisch** [mayfieldrobotics/ros-webrtc#41]
in libjingle there is `VideoCaptureModule::SetCaptureRotation(VideoCaptureRotation)` where `VideoCaptureRotation` is:

``` C
enum VideoCaptureRotation
{
    kCameraRotate0 = 0,
    kCameraRotate90 = 5,
    kCameraRotate180 = 10,
    kCameraRotate270 = 15
};
```

is should be set / camera like e.g.:

``` yaml
cameras:
  webcam:
    name: sys://BisonCam, NB Pro
    label: webcam
    rotation: 0|90|180|270
```

and since we need to fiddle w/ `DeviceManager`'s `VideoCaptureModule` changes are ~:
- https://github.com/mayfieldrobotics/ros-webrtc/blob/develop/src/host.cpp#L253-L256 and
- https://github.com/mayfieldrobotics/ros-webrtc/blob/develop/src/host.cpp#L270-L272
